// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paocizhlgeskhdqaecsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhb2NpemhsZ2Vza2hkcWFlY3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTUwMzcsImV4cCI6MjA3MTQzMTAzN30.J54g76dAZPNugggNKnARzjisbo0_kL_fnL6_yfSglrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});